namespace = "http://example.com/"

[classes.Recipe]
name = "string"
wasDerivedFromURL = "string"
[classes.Recipe.hasAuthor]
kind = "reference"
label = "Author"
cardinality = "optional"
[classes.Recipe.hasSource]
kind = "reference"
label = "Webpage"
cardinality = "optional"
[classes.Recipe.hasIngredient]
kind = "reference"
label = "Ingredient"
cardinality = "any"
[classes.Recipe.hasAssociatedTags]
kind = "reference"
label = "Tag"
cardinality = "any"

[classes.Ingredient]
name = "string"
containsMeat = "boolean"
containsNuts = "boolean"
[classes.Ingredient.hasSubstitution]
kind = "reference"
label = "Substitution"
cardinality = "any"

[classes.Substitution]
[classes.Substitution.inContext]
kind = "reference"
label = "Tag"
cardinality = "optional"
[classes.Substitution.substitutionIngredient]
kind = "reference"
label = "Ingredient"
cardinality = "any"

[classes.Webpage]
url = "string"

[classes.Author]
name = "string"

[classes.Tag]
name = "string"
hasType = "string"