namespace ul http://underlay.org/

class ul:recipe {
  ul:name -> string ;
  ul:author -> string ;
}

class ul:ingredient {
  ul:name -> string ;
}

class ul:webpage {
  ul:name -> string ;
}

class ul:tag {
  ul:name -> string ;
}

edge ul:recipe ==/ ul:hasIngredient /=> ul:ingredient
edge ul:recipe ==/ ul:hasSource /=> ul:webpage
edge ul:recipe ==/ ul:hasAssociatedTags /=> ul:tag